apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: twoge
spec:
  type: NodePort
  selector:
    app: twoge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
