apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: twoge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        envFrom:
        - configMapRef:
            name: twoge-config
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -p
            - "5432"
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
