apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: twoge
spec:
  selector:
    app: postgres
  ports:
    - name: db-port
      protocol: TCP
      port: 5432
      targetPort: 5432

